### ISSUE TITLE
Issue when scrolling back to specific calendar

### ISSUE THREAD

**Issue by aviaryan** [ansarimofid/calendar-2017#1]
This is what I see when I click on "August" in the footer.

![screen shot 2017-01-24 at 4 40 29 pm](https://cloud.githubusercontent.com/assets/4047597/22245111/57926cee-e254-11e6-8564-5706369659d2.jpg)

This is what I expect:

![screen shot 2017-01-24 at 4 41 10 pm](https://cloud.githubusercontent.com/assets/4047597/22245114/58572002-e254-11e6-8ef1-aa6e916c83fa.jpg)

Was this behaviour intentional?

**Comment by ansarimofid** [comment]
Fixed by #3
